api:
  id: "17605384"
  
http:
  host: "0.0.0.0"
  port: "8081"
  path: "/api/*"
  timeout: "30000"

fakestore:
  api:
    checkout:
      host: "fakestore-db-ws-gap.sg-s1.cloudhub.io"
      port: ""
      path: "api"