api:
  id: "17552500"
  
http:
  host: "0.0.0.0"
  port: "8081"
  path: "/api/*"
  timeout: "30000"

fakestore:
  api:
    cart:
      host: "gap-fakestore-carts-papi-v1.sg-s1.cloudhub.io"
      port: ""
      path: "api"
    product:
      host: "gap-fakestore-products-papi-v1.sg-s1.cloudhub.io"
      port: ""
      path: "api"