#fakestore api
fakestore:
  api:
    until.successful:
      attempts: "1"
      interval: "500"
    timeout: "30000"

http:
  response:
    internal.server:
      code: "500"
      msg: "Internal Server Error"
    service.unavailable:
      code: "503"
      msg: "Service Unavailable"
    bad.request:
      code: "400"
      msg: "Bad Request"
    resource.not.found:
      code: "404"
      msg: "Resource Not Found"
    method.not.allowed:
      code: "405"
      msg: "Method Not Allowed"
    not.acceptable:
      code: "406"
      msg: "Not Acceptable"
    unsupported.media.type:
      code: "415"
      msg: "Unsupported Media Type"
    not.implemented:
      code: "501"
      msg: "Not Implemented"
    header:
      api:
        name: "Fakestore Webstore Experience API"
        version: "1.0.0"
    data:
      msg:
        create: "Cart created successfully."
        update: "Cart updated successfully."
        deleted: "Cart deleted successfully."
        checkout: "Transaction was executed successfully."
        
        
      

  