api:
  id: "17552500"

http:
  host: "0.0.0.0"
  port: "8084"
  path: "/api/*"
  timeout: "30000"

fakestore:
  api:
    cart:
      host: "localhost"
      port: "8082"
      path: "api"
    product:
      host: "localhost"
      port: "8083"
      path: "api"