api:
  id: "17601059"

http:
  host: "0.0.0.0"
  port: "8081"
  path: "/api/*"
  timeout: "30000"

fakestore:
  db:
    host: "localhost"
    port: "3306"
    schema: "fakestoredb"
    until.successful:
        attempts: "1"
        interval: "500"